[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dice-mini"
version = "0.3.0"
description = "DICE mini"
authors = [{ name = "Ricardo Yaben", email = "rmyl@dtu.dk" }]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    # TODO: we will try to remove these dependencies
    "pandas", # dice
    "numpy", # dice
    "tabulate",
    "pyarrow",

    "lark",
    "tqdm",
    "ujson",
    "sqlmodel",
    "sqlalchemy",
    "dacite",
    "cryptography",
    "tomlkit",
    "cyclopts"
]

[tool.pyright]
typeCheckingMode = "standard"

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
include = ["dice", "dice.*", "modules", "modules.*", "cli", "cli.*", "config", "config.*"]
exclude = ["analysis", "analysis.*"]

[project.urls]
Homepage = "https://github.com/RicYaben/dice-mini"
Issues = "https://github.com/RicYaben/dice-mini/issues"

[project.optional-dependencies]
analysis = [
    "plotly",
    "squarify",
    "netgraph",
    "hilbertcurve",
]

[project.scripts]
dice-mini = "cli.main:main"
